/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActionsRouteImport } from './routes/_authenticated/actions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEvidenceRouteImport } from './routes/_authenticated/evidence'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedApplyRoleIdRouteImport } from './routes/_authenticated/apply.$roleId'
import { Route as AuthenticatedInterviewRoleIdRouteImport } from './routes/_authenticated/interview.$roleId'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles.index'
import { Route as AuthenticatedRolesRoleIdRouteImport } from './routes/_authenticated/roles.$roleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActionsRoute = AuthenticatedActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvidenceRoute = AuthenticatedEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyRoleIdRoute =
  AuthenticatedApplyRoleIdRouteImport.update({
    id: '/apply/$roleId',
    path: '/apply/$roleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewRoleIdRoute =
  AuthenticatedInterviewRoleIdRouteImport.update({
    id: '/interview/$roleId',
    path: '/interview/$roleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoleIdRoute =
  AuthenticatedRolesRoleIdRouteImport.update({
    id: '/roles/$roleId',
    path: '/roles/$roleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evidence': typeof AuthenticatedEvidenceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/apply/$roleId': typeof AuthenticatedApplyRoleIdRoute
  '/interview/$roleId': typeof AuthenticatedInterviewRoleIdRoute
  '/roles/$roleId': typeof AuthenticatedRolesRoleIdRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evidence': typeof AuthenticatedEvidenceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/apply/$roleId': typeof AuthenticatedApplyRoleIdRoute
  '/interview/$roleId': typeof AuthenticatedInterviewRoleIdRoute
  '/roles/$roleId': typeof AuthenticatedRolesRoleIdRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/actions': typeof AuthenticatedActionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evidence': typeof AuthenticatedEvidenceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/apply/$roleId': typeof AuthenticatedApplyRoleIdRoute
  '/_authenticated/interview/$roleId': typeof AuthenticatedInterviewRoleIdRoute
  '/_authenticated/roles/$roleId': typeof AuthenticatedRolesRoleIdRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/actions'
    | '/dashboard'
    | '/evidence'
    | '/settings'
    | '/apply/$roleId'
    | '/interview/$roleId'
    | '/roles/$roleId'
    | '/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/actions'
    | '/dashboard'
    | '/evidence'
    | '/settings'
    | '/apply/$roleId'
    | '/interview/$roleId'
    | '/roles/$roleId'
    | '/roles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/actions'
    | '/_authenticated/dashboard'
    | '/_authenticated/evidence'
    | '/_authenticated/settings'
    | '/_authenticated/apply/$roleId'
    | '/_authenticated/interview/$roleId'
    | '/_authenticated/roles/$roleId'
    | '/_authenticated/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evidence': {
      id: '/_authenticated/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AuthenticatedEvidenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/$roleId': {
      id: '/_authenticated/apply/$roleId'
      path: '/apply/$roleId'
      fullPath: '/apply/$roleId'
      preLoaderRoute: typeof AuthenticatedApplyRoleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$roleId': {
      id: '/_authenticated/interview/$roleId'
      path: '/interview/$roleId'
      fullPath: '/interview/$roleId'
      preLoaderRoute: typeof AuthenticatedInterviewRoleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/$roleId': {
      id: '/_authenticated/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof AuthenticatedRolesRoleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActionsRoute: typeof AuthenticatedActionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvidenceRoute: typeof AuthenticatedEvidenceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedApplyRoleIdRoute: typeof AuthenticatedApplyRoleIdRoute
  AuthenticatedInterviewRoleIdRoute: typeof AuthenticatedInterviewRoleIdRoute
  AuthenticatedRolesRoleIdRoute: typeof AuthenticatedRolesRoleIdRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActionsRoute: AuthenticatedActionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvidenceRoute: AuthenticatedEvidenceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedApplyRoleIdRoute: AuthenticatedApplyRoleIdRoute,
  AuthenticatedInterviewRoleIdRoute: AuthenticatedInterviewRoleIdRoute,
  AuthenticatedRolesRoleIdRoute: AuthenticatedRolesRoleIdRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
